exp_dir: /misiones/Series/Models/TimeDiffusion/
local: false
projectconf:
  total_limit: 2
accelerator:
  gradient_accumulation_steps: 1
  mixed_precision: 'no'
  log_with: wandb
samples:
  samples_freq: 500
  samples_num: 20
  samples_gen: 1000
  sample_time: 1
  sample_batch_size: 1024
time: 12
train:
  num_epochs: 50000
  log_interval: 10
  save_interval: 10
  checkpoint_freq: 2000
  checkpoint_epoch_freq: 10
  best_model: true

defaults:
  - dataloader: batch128
  - optimizer: adamw-lr4
  - loss: L2
  - lr_scheduler: cosine-w100
  - _self_